//tagList: ["취준", "토익", "공무원", "코딩", "기술사", "자격증", "수능", "고시", "오프라인"]

const tileData = [
    {
        img: "./pomodoro.png",
        id: "1",
        title: "경주의 공부방",
        author: "경쥬",
        tag: ["취준", "영어"],
    },
    {
        id: "2",
        img: "./pomodoro.png",
        title: "트와이스 나연",
        author: "경쥬",
        tag: ["코딩", "오프라인"],
    },
    {
        img: "./pomodoro.png",
        id: "3",
        title: "애스파 카리나",
        author: "경쥬",
        tag: ["취준", "토익", "공무원"],
    },
    {
        id: "4",
        img: "./pomodoro.png",
        title: "레드벨벳 조이",
        author: "경쥬",
        tag: ["고시"],
    },
    {
        id: "5",
        img: "./pomodoro.png",
        title: "혜유니의 공부방",
        author: "경쥬",
        tag: ["공무원", "코딩"],
    },
    {
        id: "6",
        img: "./pomodoro.png",
        title: "혜지의 공부방",
        author: "경쥬",
        tag: ["코딩", "기술사", "자격증"],
    },
    {
        id: "7",
        img: "./pomodoro.png",
        title: "수비니의 공부방",
        author: "경쥬",
        tag: ["수능", "고시"],
    },
    {
        id: "8",
        img: "./pomodoro.png",
        title: "지후니의 공부방",
        author: "경쥬",
        tag: ["오프라인", "코딩"],
    },
    {
        id: "9",
        img: "./pomodoro.png",
        title: "미노의 공부방",
        author: "경쥬",
        tag: ["코딩"],
    },
    {
        id: "10",
        img: "./pomodoro.png",
        title: "뚝별이의 공부방",
        author: "경쥬",
        tag: ["공무원", "코딩"],
    },
    {
        id: "11",
        img: "./pomodoro.png",
        title: "승후니의 공부방",
        author: "경쥬",
        tag: ["취준", "토익", "공무원", "코딩"],
    },
    {
        id: "12",
        img: "./pomodoro.png",
        title: "여자친구 예린",
        author: "경쥬",
        tag: ["자격증", "수능"],
    },
    {
        id: "13",
        img: "./pomodoro.png",
        title: "오마이걸 유아",
        author: "경쥬",
        tag: ["취준", "토익"],
    },
    {
        id: "14",
        img: "./pomodoro.png",
        title: "러블리즈 미주",
        author: "경쥬",
        tag: ["수능", "고시"],
    },
    {
        id: "15",
        img: "./pomodoro.png",
        title: "페이커와 류",
        author: "제드",
        tag: ["기술사", "자격증"],
    },
    {
        id: "16",
        img: "./pomodoro.png",
        title: "오마이걸 유아",
        author: "경쥬",
        tag: ["자격증", "수능"],
    },
    {
        id: "17",
        img: "./pomodoro.png",
        title: "있지 류진",
        author: "경쥬",
        tag: ["토익"],
    },
    {
        id: "18",
        img: "./pomodoro.png",
        title: "블랙핑크 리사",
        author: "경쥬",
        tag: ["자격증", "토익"],
    },
    {
        id: "19",
        img: "./pomodoro.png",
        title: "아이즈원 장원영",
        author: "경쥬",
        tag: ["취준", "토익"],
    },
    {
        id: "20",
        img: "./pomodoro.png",
        title: "(여자)아이들 소연",
        author: "경쥬",
        tag: ["공무원"],
    },
];

export default tileData;
